buildbotmaster:
    extends:
        file: ./common/docker-compose.yml
        service: buildbotmaster

buildbotslave:
    extends:
        file: ./common/docker-compose.yml
        service: buildbotslave
    links:
        - buildbotmaster

