web:
    name: pyramid
    detach: True
    binds: 
        /var/run/docker.sock:
            bind: /var/run/docker.sock
            ro: False
#    ports:
#        6543:
#        - 0.0.0.0
#        - 8090
